# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{DBcache}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Miguel Vazquez"]
  s.date = %q{2009-10-29}
  s.description = %q{Creates a table and stores and retrieves de data on the hash. It can guess the best field type.}
  s.email = %q{miguel.vazquez@fdi.ucm.es}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/DBcache.rb"
  ]
  s.homepage = %q{http://github.com/mikisvaz/DBcache}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Cache Hashes into Mysql}
  s.test_files = [
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mysql>, ["< 2.8"])
    else
      s.add_dependency(%q<mysql>, ["< 2.8"])
    end
  else
    s.add_dependency(%q<mysql>, ["< 2.8"])
  end
end

